spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/devops?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root